import Model.PlaceModel;
global java.util.List resultList;
global Db.PlaceDbContext db;
global org.kie.api.runtime.StatelessKieSession ks;
global Controller.RuleController rc;

rule "String"
    when
        $s:String($s == "real")
    then
        for(PlaceModel m : db.findByActivity(1)) resultList.add(m);
end

rule "String2"
    when
        $s:String($s == "eat")
    then
        for(PlaceModel m : db.findByActivity(2)) resultList.add(m);

end

rule "String3"
    when
        $s:String($s == "research")
    then
        for(PlaceModel m : db.findByActivity(3)) resultList.add(m);

end