global java.util.List resultList;
global Db.PlaceDbContext db;
global org.kie.api.runtime.StatelessKieSession ks;
global Controller.RuleController rc;

rule "String"
    when
        $s:String($s == "John")
    then
         for(int i = 0 ; i < 10 ; i++){
            if (db.findById(i).getAct()==1)
             resultList.add(db.findById(i));
            }
end

rule "String2"
    when
        $s:String($s == "Fish")
    then
    for(int i = 0 ; i < 10 ; i++){
    if (db.findById(i).getAct()==2)
     resultList.add(db.findById(i));
    }

end